server: 
  port: 8051


  

spring: 
  application: 
    name: user
  jpa:
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true 
  datasource: 
    url: jdbc:mysql://localhost:3306/pharmacy2021?useSSL=false&createDatabaseIfNotExist=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: ivana123
    initialization-mode: always
  mail:
    host: smtp.gmail.com
    username: no.reply.medclinic@gmail.com
    password: sifra123
    port: 587
    properties:
      mail: 
        smtp:
          ssl.trust: smtp.gmail.com
          auth: true
          starttls.enable: true

penalty:
    cron: 0 20 */1 * * * 
resetpenalty:
    cron: 0 0 0 1 * * 