sudo: required
language: java
jdk: oraclejdk8


before_install:
  - chmod +x mvnw

  
addons:
  sonarcloud:
  organization: ivanatomic43-github
  token: $MY_SONAR_TOKEN

script:
  - ./mvnw clean install -DskipTests=false -B
   - ./mvnw sonar:sonar -Dsonar.projectKey=$PROJECT_KEY -Dsonar.organization=<ivanatomic43-github> -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$MY_SONAR_TOKEN
  

dist: trusty

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: lambda-pharmacy